
function y = create_inputs (x, u, tac)
  if nargin < 3
    tac = [];
  end
  k = 1;
  if strcmp (x, 'GenericInputFunction')
    voxulus ('select', 'input', x);
    voxulus ('set', 'input', 'unit', u);
      b = [ 1 2 3 4 5 6 ];
      n = size (b, 2);
      y = cell (n + n * n, 1);
      for i=1:n
        name = sprintf ('GIF%02d', k);
        voxulus ('create', 'input', name, 'GenericInputFunction', 5);
        voxulus ('select', 'input', name);
        voxulus ('set', 'input', 'tau', 'value', 1);
        voxulus ('set', 'input', 'tau', 'initvalue', 1);
        voxulus ('set', 'input', 'tau', 'unit', 's');
        voxulus ('set', 'input', 'tau', 'state', 'const');
        voxulus ('set', 'input', 't0', 'value', 0);
        voxulus ('set', 'input', 't0', 'initvalue', 0);
        voxulus ('set', 'input', 't0', 'unit', 's');
        voxulus ('set', 'input', 't0', 'state', 'const');
        voxulus ('set', 'input', 'B1', 'value', b(i));
        voxulus ('set', 'input', 'B1', 'initvalue', b(i));
        voxulus ('set', 'input', 'B1', 'state', 'const');
        y{k} = name;
        k = k + 1;
        for j = 1:i
          name = sprintf ('GIF%02d', k);
          voxulus ('create', 'input', name, 'GenericInputFunction', 8);
          voxulus ('select', 'input', name);
          voxulus ('set', 'input', 'tau', 'value', 1);
          voxulus ('set', 'input', 'tau', 'initvalue', 1);
          voxulus ('set', 'input', 'tau', 'unit', 's');
          voxulus ('set', 'input', 'tau', 'state', 'const');
          voxulus ('set', 'input', 't0', 'value', 0);
          voxulus ('set', 'input', 't0', 'initvalue', 0);
          voxulus ('set', 'input', 't0', 'unit', 's');
          voxulus ('set', 'input', 't0', 'state', 'const');
          voxulus ('set', 'input', 'B1', 'value', b(i));
          voxulus ('set', 'input', 'B1', 'initvalue', b(i));
          voxulus ('set', 'input', 'B1', 'state', 'const');
          voxulus ('set', 'input', 'B2', 'value', b(j));
          voxulus ('set', 'input', 'B2', 'initvalue', b(j));
          voxulus ('set', 'input', 'B2', 'state', 'const');
          y{k} = name;
          k = k + 1;
        end
        name = sprintf ('GIF%02d', k);
        voxulus ('create', 'input', name, 'GenericInputFunction', 11);
        voxulus ('select', 'input', name);
        voxulus ('set', 'input', 'tau', 'value', 1);
        voxulus ('set', 'input', 'tau', 'initvalue', 1);
        voxulus ('set', 'input', 'tau', 'unit', 's');
        voxulus ('set', 'input', 'tau', 'state', 'const');
        voxulus ('set', 'input', 't0', 'value', 0);
        voxulus ('set', 'input', 't0', 'initvalue', 0);
        voxulus ('set', 'input', 't0', 'unit', 's');
        voxulus ('set', 'input', 't0', 'state', 'const');
        voxulus ('set', 'input', 'B1', 'value', b(i));
        voxulus ('set', 'input', 'B1', 'initvalue', b(i));
        voxulus ('set', 'input', 'B1', 'state', 'const');
        voxulus ('set', 'input', 'B2', 'value', 0.0);
        voxulus ('set', 'input', 'B2', 'initvalue', 0.0);
        voxulus ('set', 'input', 'B2', 'state', 'const');
        voxulus ('set', 'input', 'B3', 'value', 0.0);
        voxulus ('set', 'input', 'B3', 'initvalue', 0.0);
        voxulus ('set', 'input', 'B3', 'state', 'const');
        y{k} = name;
        k = k + 1;
        name = sprintf ('GIF%02d', k);
        voxulus ('create', 'input', name, 'GenericInputFunction', 11);
        voxulus ('select', 'input', name);
        voxulus ('set', 'input', 'tau', 'value', 1);
        voxulus ('set', 'input', 'tau', 'initvalue', 1);
        voxulus ('set', 'input', 'tau', 'unit', 's');
        voxulus ('set', 'input', 'tau', 'state', 'const');
        voxulus ('set', 'input', 't0', 'value', 0);
        voxulus ('set', 'input', 't0', 'initvalue', 0);
        voxulus ('set', 'input', 't0', 'unit', 's');
        voxulus ('set', 'input', 't0', 'state', 'const');
        voxulus ('set', 'input', 'B1', 'value', b(i));
        voxulus ('set', 'input', 'B1', 'initvalue', b(i));
        voxulus ('set', 'input', 'B1', 'state', 'const');
        voxulus ('set', 'input', 'A2', 'link-', 'A3');
        voxulus ('set', 'input', 'B2', 'value', 0.0);
        voxulus ('set', 'input', 'B2', 'initvalue', 0.0);
        voxulus ('set', 'input', 'B2', 'state', 'const');
        voxulus ('set', 'input', 'B3', 'value', 0.0);
        voxulus ('set', 'input', 'B3', 'initvalue', 0.0);
        voxulus ('set', 'input', 'B3', 'state', 'const');
        y{k} = name;
        k = k + 1;
        name = sprintf ('GIF%02d', k);
        voxulus ('create', 'input', name, 'GenericInputFunction', 17);
        voxulus ('select', 'input', name);
        voxulus ('set', 'input', 'tau', 'value', 1);
        voxulus ('set', 'input', 'tau', 'initvalue', 1);
        voxulus ('set', 'input', 'tau', 'unit', 's');
        voxulus ('set', 'input', 'tau', 'state', 'const');
        voxulus ('set', 'input', 't0', 'value', 0);
        voxulus ('set', 'input', 't0', 'initvalue', 0);
        voxulus ('set', 'input', 't0', 'unit', 's');
        voxulus ('set', 'input', 't0', 'state', 'const');
        voxulus ('set', 'input', 'B1', 'value', b(i));
        voxulus ('set', 'input', 'B1', 'initvalue', b(i));
        voxulus ('set', 'input', 'B1', 'state', 'const');
        voxulus ('set', 'input', 'B2', 'value', 0.0);
        voxulus ('set', 'input', 'B2', 'initvalue', 0.0);
        voxulus ('set', 'input', 'B2', 'state', 'const');
        voxulus ('set', 'input', 'B3', 'value', 0.0);
        voxulus ('set', 'input', 'B3', 'initvalue', 0.0);
        voxulus ('set', 'input', 'B3', 'state', 'const');
        voxulus ('set', 'input', 'B4', 'value', 0.0);
        voxulus ('set', 'input', 'B4', 'initvalue', 0.0);
        voxulus ('set', 'input', 'B4', 'state', 'const');
        voxulus ('set', 'input', 'B5', 'value', 0.0);
        voxulus ('set', 'input', 'B5', 'initvalue', 0.0);
        voxulus ('set', 'input', 'B5', 'state', 'const');
        y{k} = name;
        k = k + 1;
        name = sprintf ('GIF%02d', k);
        voxulus ('create', 'input', name, 'GenericInputFunction', 17);
        voxulus ('select', 'input', name);
        voxulus ('set', 'input', 'tau', 'value', 1);
        voxulus ('set', 'input', 'tau', 'initvalue', 1);
        voxulus ('set', 'input', 'tau', 'unit', 's');
        voxulus ('set', 'input', 'tau', 'state', 'const');
        voxulus ('set', 'input', 't0', 'value', 0);
        voxulus ('set', 'input', 't0', 'initvalue', 0);
        voxulus ('set', 'input', 't0', 'unit', 's');
        voxulus ('set', 'input', 't0', 'state', 'const');
        voxulus ('set', 'input', 'B1', 'value', b(i));
        voxulus ('set', 'input', 'B1', 'initvalue', b(i));
        voxulus ('set', 'input', 'B1', 'state', 'const');
        voxulus ('set', 'input', 'A2', 'link-', 'A3');
        voxulus ('set', 'input', 'B2', 'value', 0.0);
        voxulus ('set', 'input', 'B2', 'initvalue', 0.0);
        voxulus ('set', 'input', 'B2', 'state', 'const');
        voxulus ('set', 'input', 'B3', 'value', 0.0);
        voxulus ('set', 'input', 'B3', 'initvalue', 0.0);
        voxulus ('set', 'input', 'B3', 'state', 'const');
        voxulus ('set', 'input', 'A4', 'link-', 'A5');
        voxulus ('set', 'input', 'B4', 'value', 0.0);
        voxulus ('set', 'input', 'B4', 'initvalue', 0.0);
        voxulus ('set', 'input', 'B4', 'state', 'const');
        voxulus ('set', 'input', 'B5', 'value', 0.0);
        voxulus ('set', 'input', 'B5', 'initvalue', 0.0);
        voxulus ('set', 'input', 'B5', 'state', 'const');
        y{k} = name;
        k = k + 1;
      end
  elseif strcmp (x, 'FMISO_InputFunction')
    k = 1;
    name = sprintf ('FMISO%02d', k);
    voxulus ('create', 'input', name, 'FMISO_InputFunction', 3);
    voxulus ('select', 'input', name);
    voxulus ('set', 'input', 'tau', 'value', 1);
    voxulus ('set', 'input', 'tau', 'initvalue', 1);
    voxulus ('set', 'input', 'tau', 'unit', 's');
    voxulus ('set', 'input', 'tau', 'state', 'const');
    voxulus ('set', 'input', 'A0', 'unit', u);
    y{k} = name;     
    k = 2;
    name = sprintf ('FMISO%02d', k);
    voxulus ('create', 'input', name, 'FMISO_InputFunction', 6);
    voxulus ('select', 'input', name);
    voxulus ('set', 'input', 'tau', 'value', 1);
    voxulus ('set', 'input', 'tau', 'initvalue', 1);
    voxulus ('set', 'input', 'tau', 'unit', 's');
    voxulus ('set', 'input', 'tau', 'state', 'const');
    voxulus ('set', 'input', 'A0', 'unit', u);
    voxulus ('set', 'input', 'A1', 'unit', u);
    y{k} = name;     
    k = 3;
    name = sprintf ('FMISO%02d', k);
    voxulus ('create', 'input', name, 'FMISO_InputFunction', 9);
    voxulus ('select', 'input', name);
    voxulus ('set', 'input', 'tau', 'value', 1);
    voxulus ('set', 'input', 'tau', 'initvalue', 1);
    voxulus ('set', 'input', 'tau', 'unit', 's');
    voxulus ('set', 'input', 'tau', 'state', 'const');
    voxulus ('set', 'input', 'A0', 'unit', u);
    voxulus ('set', 'input', 'A1', 'unit', u);
    voxulus ('set', 'input', 'A2', 'unit', u);          
    y{k} = name;     
  else
    error ('unknown input function class ''%s''', x);
  end
